<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $isoMap = [
            'Afghanistan' => ['iso' => 'AF', 'iso3' => 'AFG'],
            'Albania' => ['iso' => 'AL', 'iso3' => 'ALB'],
            'Algeria' => ['iso' => 'DZ', 'iso3' => 'DZA'],
            'Andorra' => ['iso' => 'AD', 'iso3' => 'AND'],
            'Angola' => ['iso' => 'AO', 'iso3' => 'AGO'],
            'Antigua and Barbuda' => ['iso' => 'AG', 'iso3' => 'ATG'],
            'Argentina' => ['iso' => 'AR', 'iso3' => 'ARG'],
            'Armenia' => ['iso' => 'AM', 'iso3' => 'ARM'],
            'Australia' => ['iso' => 'AU', 'iso3' => 'AUS'],
            'Austria' => ['iso' => 'AT', 'iso3' => 'AUT'],
            'Azerbaijan' => ['iso' => 'AZ', 'iso3' => 'AZE'],
            'Bahamas' => ['iso' => 'BS', 'iso3' => 'BHS'],
            'Bahrain' => ['iso' => 'BH', 'iso3' => 'BHR'],
            'Bangladesh' => ['iso' => 'BD', 'iso3' => 'BGD'],
            'Barbados' => ['iso' => 'BB', 'iso3' => 'BRB'],
            'Belarus' => ['iso' => 'BY', 'iso3' => 'BLR'],
            'Belgium' => ['iso' => 'BE', 'iso3' => 'BEL'],
            'Belize' => ['iso' => 'BZ', 'iso3' => 'BLZ'],
            'Benin' => ['iso' => 'BJ', 'iso3' => 'BEN'],
            'Bhutan' => ['iso' => 'BT', 'iso3' => 'BTN'],
            'Bolivia' => ['iso' => 'BO', 'iso3' => 'BOL'],
            'Bosnia and Herzegovina' => ['iso' => 'BA', 'iso3' => 'BIH'],
            'Botswana' => ['iso' => 'BW', 'iso3' => 'BWA'],
            'Brazil' => ['iso' => 'BR', 'iso3' => 'BRA'],
            'Brunei' => ['iso' => 'BN', 'iso3' => 'BRN'],
            'Bulgaria' => ['iso' => 'BG', 'iso3' => 'BGR'],
            'Burkina Faso' => ['iso' => 'BF', 'iso3' => 'BFA'],
            'Burundi' => ['iso' => 'BI', 'iso3' => 'BDI'],
            'Cambodia' => ['iso' => 'KH', 'iso3' => 'KHM'],
            'Cameroon' => ['iso' => 'CM', 'iso3' => 'CMR'],
            'Canada' => ['iso' => 'CA', 'iso3' => 'CAN'],
            'Cape Verde' => ['iso' => 'CV', 'iso3' => 'CPV'],
            'Central African Republic' => ['iso' => 'CF', 'iso3' => 'CAF'],
            'Chad' => ['iso' => 'TD', 'iso3' => 'TCD'],
            'Chile' => ['iso' => 'CL', 'iso3' => 'CHL'],
            'China' => ['iso' => 'CN', 'iso3' => 'CHN'],
            'Colombia' => ['iso' => 'CO', 'iso3' => 'COL'],
            'Comoros' => ['iso' => 'KM', 'iso3' => 'COM'],
            'Congo (Brazzaville)' => ['iso' => 'CG', 'iso3' => 'COG'],
            'Congo (Kinshasa)' => ['iso' => 'CD', 'iso3' => 'COD'],
            'Costa Rica' => ['iso' => 'CR', 'iso3' => 'CRI'],
            'Croatia' => ['iso' => 'HR', 'iso3' => 'HRV'],
            'Cuba' => ['iso' => 'CU', 'iso3' => 'CUB'],
            'Cyprus' => ['iso' => 'CY', 'iso3' => 'CYP'],
            'Czech Republic' => ['iso' => 'CZ', 'iso3' => 'CZE'],
            'Denmark' => ['iso' => 'DK', 'iso3' => 'DNK'],
            'Djibouti' => ['iso' => 'DJ', 'iso3' => 'DJI'],
            'Dominica' => ['iso' => 'DM', 'iso3' => 'DMA'],
            'Dominican Republic' => ['iso' => 'DO', 'iso3' => 'DOM'],
            'Ecuador' => ['iso' => 'EC', 'iso3' => 'ECU'],
            'Egypt' => ['iso' => 'EG', 'iso3' => 'EGY'],
            'El Salvador' => ['iso' => 'SV', 'iso3' => 'SLV'],
            'Equatorial Guinea' => ['iso' => 'GQ', 'iso3' => 'GNQ'],
            'Eritrea' => ['iso' => 'ER', 'iso3' => 'ERI'],
            'Estonia' => ['iso' => 'EE', 'iso3' => 'EST'],
            'Eswatini' => ['iso' => 'SZ', 'iso3' => 'SWZ'],
            'Ethiopia' => ['iso' => 'ET', 'iso3' => 'ETH'],
            'Fiji' => ['iso' => 'FJ', 'iso3' => 'FJI'],
            'Finland' => ['iso' => 'FI', 'iso3' => 'FIN'],
            'France' => ['iso' => 'FR', 'iso3' => 'FRA'],
            'Gabon' => ['iso' => 'GA', 'iso3' => 'GAB'],
            'Gambia' => ['iso' => 'GM', 'iso3' => 'GMB'],
            'Georgia' => ['iso' => 'GE', 'iso3' => 'GEO'],
            'Germany' => ['iso' => 'DE', 'iso3' => 'DEU'],
            'Ghana' => ['iso' => 'GH', 'iso3' => 'GHA'],
            'Greece' => ['iso' => 'GR', 'iso3' => 'GRC'],
            'Grenada' => ['iso' => 'GD', 'iso3' => 'GRD'],
            'Guatemala' => ['iso' => 'GT', 'iso3' => 'GTM'],
            'Guinea' => ['iso' => 'GN', 'iso3' => 'GIN'],
            'Guinea-Bissau' => ['iso' => 'GW', 'iso3' => 'GNB'],
            'Guyana' => ['iso' => 'GY', 'iso3' => 'GUY'],
            'Haiti' => ['iso' => 'HT', 'iso3' => 'HTI'],
            'Honduras' => ['iso' => 'HN', 'iso3' => 'HND'],
            'Hungary' => ['iso' => 'HU', 'iso3' => 'HUN'],
            'Iceland' => ['iso' => 'IS', 'iso3' => 'ISL'],
            'India' => ['iso' => 'IN', 'iso3' => 'IND'],
            'Indonesia' => ['iso' => 'ID', 'iso3' => 'IDN'],
            'Iran' => ['iso' => 'IR', 'iso3' => 'IRN'],
            'Iraq' => ['iso' => 'IQ', 'iso3' => 'IRQ'],
            'Ireland' => ['iso' => 'IE', 'iso3' => 'IRL'],
            'Israel' => ['iso' => 'IL', 'iso3' => 'ISR'],
            'Italy' => ['iso' => 'IT', 'iso3' => 'ITA'],
            'Ivory Coast' => ['iso' => 'CI', 'iso3' => 'CIV'],
            'Jamaica' => ['iso' => 'JM', 'iso3' => 'JAM'],
            'Japan' => ['iso' => 'JP', 'iso3' => 'JPN'],
            'Jordan' => ['iso' => 'JO', 'iso3' => 'JOR'],
            'Kazakhstan' => ['iso' => 'KZ', 'iso3' => 'KAZ'],
            'Kenya' => ['iso' => 'KE', 'iso3' => 'KEN'],
            'Kiribati' => ['iso' => 'KI', 'iso3' => 'KIR'],
            'Kuwait' => ['iso' => 'KW', 'iso3' => 'KWT'],
            'Kyrgyzstan' => ['iso' => 'KG', 'iso3' => 'KGZ'],
            'Laos' => ['iso' => 'LA', 'iso3' => 'LAO'],
            'Latvia' => ['iso' => 'LV', 'iso3' => 'LVA'],
            'Lebanon' => ['iso' => 'LB', 'iso3' => 'LBN'],
            'Lesotho' => ['iso' => 'LS', 'iso3' => 'LSO'],
            'Liberia' => ['iso' => 'LR', 'iso3' => 'LBR'],
            'Libya' => ['iso' => 'LY', 'iso3' => 'LBY'],
            'Liechtenstein' => ['iso' => 'LI', 'iso3' => 'LIE'],
            'Lithuania' => ['iso' => 'LT', 'iso3' => 'LTU'],
            'Luxembourg' => ['iso' => 'LU', 'iso3' => 'LUX'],
            'Madagascar' => ['iso' => 'MG', 'iso3' => 'MDG'],
            'Malawi' => ['iso' => 'MW', 'iso3' => 'MWI'],
            'Malaysia' => ['iso' => 'MY', 'iso3' => 'MYS'],
            'Maldives' => ['iso' => 'MV', 'iso3' => 'MDV'],
            'Mali' => ['iso' => 'ML', 'iso3' => 'MLI'],
            'Malta' => ['iso' => 'MT', 'iso3' => 'MLT'],
            'Marshall Islands' => ['iso' => 'MH', 'iso3' => 'MHL'],
            'Mauritania' => ['iso' => 'MR', 'iso3' => 'MRT'],
            'Mauritius' => ['iso' => 'MU', 'iso3' => 'MUS'],
            'Mexico' => ['iso' => 'MX', 'iso3' => 'MEX'],
            'Micronesia' => ['iso' => 'FM', 'iso3' => 'FSM'],
            'Moldova' => ['iso' => 'MD', 'iso3' => 'MDA'],
            'Monaco' => ['iso' => 'MC', 'iso3' => 'MCO'],
            'Mongolia' => ['iso' => 'MN', 'iso3' => 'MNG'],
            'Montenegro' => ['iso' => 'ME', 'iso3' => 'MNE'],
            'Morocco' => ['iso' => 'MA', 'iso3' => 'MAR'],
            'Mozambique' => ['iso' => 'MZ', 'iso3' => 'MOZ'],
            'Myanmar' => ['iso' => 'MM', 'iso3' => 'MMR'],
            'Namibia' => ['iso' => 'NA', 'iso3' => 'NAM'],
            'Nauru' => ['iso' => 'NR', 'iso3' => 'NRU'],
            'Nepal' => ['iso' => 'NP', 'iso3' => 'NPL'],
            'Netherlands' => ['iso' => 'NL', 'iso3' => 'NLD'],
            'New Zealand' => ['iso' => 'NZ', 'iso3' => 'NZL'],
            'Nicaragua' => ['iso' => 'NI', 'iso3' => 'NIC'],
            'Niger' => ['iso' => 'NE', 'iso3' => 'NER'],
            'Nigeria' => ['iso' => 'NG', 'iso3' => 'NGA'],
            'North Korea' => ['iso' => 'KP', 'iso3' => 'PRK'],
            'North Macedonia' => ['iso' => 'MK', 'iso3' => 'MKD'],
            'Norway' => ['iso' => 'NO', 'iso3' => 'NOR'],
            'Oman' => ['iso' => 'OM', 'iso3' => 'OMN'],
            'Pakistan' => ['iso' => 'PK', 'iso3' => 'PAK'],
            'Palau' => ['iso' => 'PW', 'iso3' => 'PLW'],
            'Palestine' => ['iso' => 'PS', 'iso3' => 'PSE'],
            'Panama' => ['iso' => 'PA', 'iso3' => 'PAN'],
            'Papua New Guinea' => ['iso' => 'PG', 'iso3' => 'PNG'],
            'Paraguay' => ['iso' => 'PY', 'iso3' => 'PRY'],
            'Peru' => ['iso' => 'PE', 'iso3' => 'PER'],
            'Philippines' => ['iso' => 'PH', 'iso3' => 'PHL'],
            'Poland' => ['iso' => 'PL', 'iso3' => 'POL'],
            'Portugal' => ['iso' => 'PT', 'iso3' => 'PRT'],
            'Qatar' => ['iso' => 'QA', 'iso3' => 'QAT'],
            'Romania' => ['iso' => 'RO', 'iso3' => 'ROU'],
            'Russia' => ['iso' => 'RU', 'iso3' => 'RUS'],
            'Rwanda' => ['iso' => 'RW', 'iso3' => 'RWA'],
            'Saint Kitts and Nevis' => ['iso' => 'KN', 'iso3' => 'KNA'],
            'Saint Lucia' => ['iso' => 'LC', 'iso3' => 'LCA'],
            'Saint Vincent and the Grenadines' => ['iso' => 'VC', 'iso3' => 'VCT'],
            'Samoa' => ['iso' => 'WS', 'iso3' => 'WSM'],
            'San Marino' => ['iso' => 'SM', 'iso3' => 'SMR'],
            'Sao Tome and Principe' => ['iso' => 'ST', 'iso3' => 'STP'],
            'Saudi Arabia' => ['iso' => 'SA', 'iso3' => 'SAU'],
            'Senegal' => ['iso' => 'SN', 'iso3' => 'SEN'],
            'Serbia' => ['iso' => 'RS', 'iso3' => 'SRB'],
            'Seychelles' => ['iso' => 'SC', 'iso3' => 'SYC'],
            'Sierra Leone' => ['iso' => 'SL', 'iso3' => 'SLE'],
            'Singapore' => ['iso' => 'SG', 'iso3' => 'SGP'],
            'Slovakia' => ['iso' => 'SK', 'iso3' => 'SVK'],
            'Slovenia' => ['iso' => 'SI', 'iso3' => 'SVN'],
            'Solomon Islands' => ['iso' => 'SB', 'iso3' => 'SLB'],
            'Somalia' => ['iso' => 'SO', 'iso3' => 'SOM'],
            'South Africa' => ['iso' => 'ZA', 'iso3' => 'ZAF'],
            'South Korea' => ['iso' => 'KR', 'iso3' => 'KOR'],
            'South Sudan' => ['iso' => 'SS', 'iso3' => 'SSD'],
            'Spain' => ['iso' => 'ES', 'iso3' => 'ESP'],
            'Sri Lanka' => ['iso' => 'LK', 'iso3' => 'LKA'],
            'Sudan' => ['iso' => 'SD', 'iso3' => 'SDN'],
            'Suriname' => ['iso' => 'SR', 'iso3' => 'SUR'],
            'Sweden' => ['iso' => 'SE', 'iso3' => 'SWE'],
            'Switzerland' => ['iso' => 'CH', 'iso3' => 'CHE'],
            'Syria' => ['iso' => 'SY', 'iso3' => 'SYR'],
            'Taiwan' => ['iso' => 'TW', 'iso3' => 'TWN'],
            'Tajikistan' => ['iso' => 'TJ', 'iso3' => 'TJK'],
            'Tanzania' => ['iso' => 'TZ', 'iso3' => 'TZA'],
            'Thailand' => ['iso' => 'TH', 'iso3' => 'THA'],
            'Timor-Leste' => ['iso' => 'TL', 'iso3' => 'TLS'],
            'Togo' => ['iso' => 'TG', 'iso3' => 'TGO'],
            'Tonga' => ['iso' => 'TO', 'iso3' => 'TON'],
            'Trinidad and Tobago' => ['iso' => 'TT', 'iso3' => 'TTO'],
            'Tunisia' => ['iso' => 'TN', 'iso3' => 'TUN'],
            'Turkey' => ['iso' => 'TR', 'iso3' => 'TUR'],
            'Turkmenistan' => ['iso' => 'TM', 'iso3' => 'TKM'],
            'Tuvalu' => ['iso' => 'TV', 'iso3' => 'TUV'],
            'Uganda' => ['iso' => 'UG', 'iso3' => 'UGA'],
            'Ukraine' => ['iso' => 'UA', 'iso3' => 'UKR'],
            'United Arab Emirates' => ['iso' => 'AE', 'iso3' => 'ARE'],
            'United Kingdom' => ['iso' => 'GB', 'iso3' => 'GBR'],
            'United States' => ['iso' => 'US', 'iso3' => 'USA'],
            'Uruguay' => ['iso' => 'UY', 'iso3' => 'URY'],
            'Uzbekistan' => ['iso' => 'UZ', 'iso3' => 'UZB'],
            'Vanuatu' => ['iso' => 'VU', 'iso3' => 'VUT'],
            'Vatican City' => ['iso' => 'VA', 'iso3' => 'VAT'],
            'Venezuela' => ['iso' => 'VE', 'iso3' => 'VEN'],
            'Vietnam' => ['iso' => 'VN', 'iso3' => 'VNM'],
            'Yemen' => ['iso' => 'YE', 'iso3' => 'YEM'],
            'Zambia' => ['iso' => 'ZM', 'iso3' => 'ZMB'],
            'Zimbabwe' => ['iso' => 'ZW', 'iso3' => 'ZWE'],
        ];

        $phoneCodes = config('countries');

        $position = 1;
        foreach ($isoMap as $name => $codes) {
            Country::firstOrCreate(
                ['iso_code' => $codes['iso']],
                [
                    'name'       => $name,
                    'iso3_code'  => $codes['iso3'],
                    'phone_code' => $phoneCodes[$name] ?? null,
                    'is_source'  => true,
                    'is_destination' => false,
                    'position'   => $position++,
                ]
            );
        }
    }
}
